package modelo.entidades;
// Generated 29 ene. 2021 11:51:03 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Ejemplar generated by hbm2java
 */
public class Ejemplar implements java.io.Serializable {

	private Integer idEjemplar;
	private Libro libro;
	private int numEjemplar;
	private String estado;
	private Set prestamos = new HashSet(0);

	public Ejemplar() {
	}

	public Ejemplar(Libro libro, int numEjemplar, String estado) {
		this.libro = libro;
		this.numEjemplar = numEjemplar;
		this.estado = estado;
	}

	public Ejemplar(Libro libro, int numEjemplar, String estado, Set prestamos) {
		this.libro = libro;
		this.numEjemplar = numEjemplar;
		this.estado = estado;
		this.prestamos = prestamos;
	}

	public Integer getIdEjemplar() {
		return this.idEjemplar;
	}

	public void setIdEjemplar(Integer idEjemplar) {
		this.idEjemplar = idEjemplar;
	}

	public Libro getLibro() {
		return this.libro;
	}

	public void setLibro(Libro libro) {
		this.libro = libro;
	}

	public int getNumEjemplar() {
		return this.numEjemplar;
	}

	public void setNumEjemplar(int numEjemplar) {
		this.numEjemplar = numEjemplar;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set getPrestamos() {
		return this.prestamos;
	}

	public void setPrestamos(Set prestamos) {
		this.prestamos = prestamos;
	}

}
